<template>
  <div :class="show ? [$style.wrap, $style.show] : $style.wrap">
    <div :class="$style.spinner">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent, ref, SetupContext } from "@vue/composition-api";

export default defineComponent({
  setup(_props: Record<string, any>, { root, refs }: SetupContext) {
    const d = {
      show: ref(false),
    };

    root.$on("loader", (show: boolean) => {
      d.show.value = show;
    });

    return d;
  },
});
</script>

<style lang="scss" module>
.wrap {
  width: 100vw;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  overflow: hidden;
  background: rgba(0, 0, 0, 0.4);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 99;
  opacity: 0;
  pointer-events: none;
  transition: 0.25s;
  &.show {
    opacity: 1;
    pointer-events: auto;
  }
}
.spinner {
  width: 0;
  height: 0;
  margin: auto;
  position: relative;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  backface-visibility: hidden;
  transform-origin: 50% 50%; /* see note above */
  transform: scale(0.7);
  @include sm() {
    top: -30px;
    transform: scale(0.5);
  }
}

@keyframes spinner {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.spinner div {
  left: 0;
  top: 0;
  position: absolute;
  box-sizing: content-box;
  background: #fff;
  width: 6px;
  height: 18px;
  border-radius: 0 / 0;
  animation: spinner linear 0.8333333333333334s infinite;
  transform-origin: 3px 33px;
}
.spinner div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.7291666666666667s;
  background: #fff;
}
.spinner div:nth-child(2) {
  transform: rotate(45deg);
  animation-delay: -0.625s;
  background: #fff;
}
.spinner div:nth-child(3) {
  transform: rotate(90deg);
  animation-delay: -0.5208333333333334s;
  background: #fff;
}
.spinner div:nth-child(4) {
  transform: rotate(135deg);
  animation-delay: -0.4166666666666667s;
  background: #fff;
}
.spinner div:nth-child(5) {
  transform: rotate(180deg);
  animation-delay: -0.3125s;
  background: #fff;
}
.spinner div:nth-child(6) {
  transform: rotate(225deg);
  animation-delay: -0.20833333333333334s;
  background: #fff;
}
.spinner div:nth-child(7) {
  transform: rotate(270deg);
  animation-delay: -0.10416666666666667s;
  background: #fff;
}
.spinner div:nth-child(8) {
  transform: rotate(315deg);
  animation-delay: 0s;
  background: #fff;
}

/* generated by https://loading.io/ */
</style>
